---
title: "Mapping"
author: "Jack Sudds"
date: "2024-11-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Packages}
if (!require("pacman")) install.packages("pacman")
library(pacman)
p_load(
  #Learning & Base
  learnr, swirl, installr,
  #File & Package Management
  here, rio, openxlsx, renv, pacman, remotes, readxl,
  #Data Management
  tidyverse, linelist, naniar, parsedate, reshape2, dplyr,
  #Stats
  janitor, gtsummary, rstatix, broom, lmtest, easystats, skimr, spatstat,
  #Plots
  cowplot, RColorBrewer, ggnewscale, wesanderson, DiagrammeR, incidence2, gghighlight, ggtext, ggrepel, gganimate, ggsci, grates, gridExtra, ggforce, hexbin, plotly,
  #GIS
  sf, tmap, spdep, rnaturalearth, rnaturalearthdata, broom, ggmap, mapdata, maps, spData, BiocManager, geoR, giscoR,
  #Reports & Dashboards
  rmarkdown, reportfactory, officer, flexdashboard, shiny,
  #tables
  knitr, flextable, formattable, gt,
  #Other
  kableExtra, psych, BSDA, htmltools, rgl, lubridate, htmlwidgets,
  #Testing
  raster, dismo, terra, CCAMLRGIS, tigris, patchwork
)

#install.packages("spDataLarge", repos = "https://nowosad.github.io/drat/", type = "source")
#install_github("ropensci/rnaturalearthhires")

theme_set(theme_linedraw())
```

```{r Grid Map}
#Create Map_Red
temp <- read_excel("Red_Map.xlsx", sheet = "Final_Data")
temp <- temp %>%
  mutate(Meta_Period = str_replace(Meta_Period, "IA/Roman", "Iron Age")) %>%
  mutate(Meta_Period = str_replace(Meta_Period, "Saxon", "Medieval")) %>%
  mutate(Meta_Period = str_replace(Meta_Period, "Norman", "Medieval"))
temp$Facet = factor(temp$Meta_Period, levels = c("Iron Age", "Roman", "Medieval", "Post_Medieval"))
Grid_Red <- temp
Grid_Red <- Grid_Red %>% drop_na()

#Bring in Roe deer
Map_Roe <- read_excel("Red_Map.xlsx", sheet = "Roe")
Map_Roe$Facet = factor(Map_Roe$Period, levels = c("Iron Age", "Roman", "Medieval", "Post_Medieval"))
Map_Roe$Long <- as.numeric(Map_Roe$Long)
Map_Roe <- Map_Roe %>% drop_na()

#Simplify
DataGrid <- Grid_Red[,c("Lat", "Long", "NISP", "Meta_Period")]
DataGrid$NISP <- as.factor(DataGrid$NISP)

#Import UK Base map
UK <- gisco_get_countries(country = "UK", resolution = 1)
#Change coord system to M
UK <- st_transform(UK, st_crs(27700))
#Create grid
UK_Grid <- UK %>%
  st_make_grid(cellsize = c(10000,10000))
UK_Grid_Map <- st_intersection(UK_Grid, UK) %>% 
  st_as_sf() %>% 
  mutate(grid_id = 1:n())
#Change coord system back to Lat/Long
UK <- st_transform(UK, st_crs("WGS84"))
UK_Grid_Map <- st_transform(UK_Grid_Map, st_crs("WGS84"))

#Make Red Deer Data Gel with the grid
weird <- DataGrid
coordinates(weird)=~Long+Lat
proj4string(weird) <- CRS("+proj=longlat +datum=WGS84")
weird <- st_as_sf(weird)

#make Roe Deer data Gel
MiniDeer <- Map_Roe[,c(4,5,6,7)]
coordinates(MiniDeer)=~Long+Lat
proj4string(MiniDeer) <- CRS("+proj=longlat +datum=WGS84")
MiniDeer <- st_as_sf(MiniDeer)

#Make Plot-able boxes (Red) removing empty ones
Red_boxes <- UK_Grid_Map %>% 
  st_join(weird) %>% 
  group_by(grid_id)
Red_boxes <- Red_boxes %>% drop_na()
Red_boxes <- Red_boxes[,c(3,1,2,4)]
Red_boxes$Meta_Period <- factor(Red_boxes$Meta_Period, levels = c("Iron Age", "Roman", "Medieval", "Post_Medieval"))

#Make Plot-able boxes (Roe) removing empty ones
Roe_boxes <- UK_Grid_Map %>% 
  st_join(MiniDeer) %>% 
  group_by(grid_id)
Roe_boxes <- Roe_boxes %>% drop_na()
Roe_boxes$Facet <- factor(Roe_boxes$Facet, levels = c("Iron Age", "Roman", "Medieval", "Post_Medieval"))

#Plot Red
ggplot() +
  geom_sf(data = UK) +
  geom_sf(data = Red_boxes, aes(fill = Meta_Period))+
  theme(
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    axis.title = element_blank(),
    panel.grid = element_blank()
  ) +
  labs(
    title = "Red Deer"
  ) +
  coord_sf(xlim = c(-8.5, 2.50), ylim = c(49.8, 60), expand = FALSE) +
  facet_wrap(~Meta_Period, nrow = 1)
ggsave("Red10km.png", dpi = 1200)

ggplot() +
  geom_sf(data = UK) +
  geom_sf(data = Red_boxes, aes(fill = Meta_Period))+
  theme(
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    axis.title = element_blank(),
    panel.grid = element_blank()
  ) +
  labs(
    title = "Red Deer"
  ) +
  coord_sf(xlim = c(-8.5, 2.50), ylim = c(49.8, 60), expand = FALSE) 
ggsave("redtest.png")

#Plot Red
ggplot() +
  geom_sf(data = UK) +
  geom_sf(data = Roe_boxes, aes(fill = Facet))+
  theme(
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    axis.title = element_blank(),
    panel.grid = element_blank()
  ) +
  labs(
    title = "Roe Deer"
  ) +
  coord_sf(xlim = c(-8.5, 2.50), ylim = c(49.8, 60), expand = FALSE) +
  facet_wrap(~Facet, nrow = 1)
  ggsave("Roe10km.png", dpi = 1200)

```

```{r ratios & Other species DATA MANAGEMENT01}
#import and tidy, names and cut out extraneous
temp <- read_excel("Red_Map.xlsx", sheet = "R_Prep")
colnames(temp)[c(1,5,6,7,8,9,10,14,17)] <- c("Site", "Bos","Ovis", "Sus", "Cervus", "Cap", "Dama", "Equid", "Total_NISP")
temp <- temp[c(1,2,3,4,5,6,7,8,9,10,14,17)]
temp <- temp[complete.cases(temp[,c("Site_Type")]),]
#add in already present location data (red then roe)
temp2 <- read_excel("Red_Map.xlsx", sheet = "Final_Data")
temp$Lat <- temp2$Lat[match(temp$Site, temp2$Site)]
temp$Long <- temp2$Long[match(temp$Site, temp2$Site)]
temp2 <- read_excel("Red_Map.xlsx", sheet = "Roe")
temp$Lat2 <- temp2$Lat[match(temp$Site, temp2$Site)]
temp$Long2 <- temp2$Long[match(temp$Site, temp2$Site)]
temp$Long2 <- as.numeric(temp$Long2)
temp <- temp %>%
  mutate(Lat = coalesce(Lat, Lat2)) %>%
  mutate(Long = coalesce(Long, Long2)) %>%
  subset(select = -c(Lat2, Long2)) %>%
  arrange(Lat)
#remove where deer absent
also <- temp[with(temp, is.na(Cervus)& is.na(Dama)& is.na(Cap)),]
#export for remaingin Lat Longs
write.xlsx(temp, "Mapping_Master.xlsx")

```

```{r ratios & Other species DATA MANAGEMENT02 ALWAYS RUN}
temp <- read_excel("Mapping_Master_Complete.xlsx")
temp <- rbind(temp, also)
temp$Meta_Period <- factor(temp$Meta_Period, levels = c("Iron Age", "Roman", "Anglo_Saxon", "Medieval", "Post_Medieval", "Modern"))
#replace NA with 0
temp[is.na(temp)] <- 0
#find complete duplicates
temp <- temp %>%
  group_by(Site, Period, Meta_Period, Site_Type) %>%
  mutate(dupe = n()>1)
#ratios
temp <- temp %>%
  mutate(CE_By_Dom = (Cervus/(Bos+Ovis+Sus+Cervus))*100) %>%
  mutate(CC_By_Dom = (Cap/(Bos+Ovis+Sus+Cap))*100) %>%
  mutate(DD_By_Dom = (Dama/(Bos+Ovis+Sus+Dama))*100) %>%
  mutate(Deer_By_Dom = ((Cervus+Cap+Dama)/(Bos+Ovis+Sus+Cervus+Cap+Dama))*100)

#ratios & total through meta-periods
Meta_Period_Ratios <- aggregate(temp[,16:19], list(temp$Meta_Period), mean)
Meta_Period_Ratios <- gather(Meta_Period_Ratios, Species, Ratio, CE_By_Dom:Deer_By_Dom, factor_key = TRUE)
Meta_Period_Ratios$Group.1 <- factor(Meta_Period_Ratios$Group.1, levels = c("Iron Age", "Roman", "Anglo_Saxon", "Medieval", "Post_Medieval", "Modern"))
Meta_Period_Tots <- aggregate(temp[,8:10], list(temp$Meta_Period), sum)
Meta_Period_Tots <- gather(Meta_Period_Tots, Species, Sum, Cervus:Dama, factor_key = TRUE)
Meta_Period_Tots$Group.1 <- factor(Meta_Period_Tots$Group.1, levels = c("Iron Age", "Roman", "Anglo_Saxon", "Medieval", "Post_Medieval", "Modern"))

#ratios through periods
Period_Ratios <- aggregate(temp[,16:19], list(temp$Period), mean)
Period_Ratios <- gather(Period_Ratios, Species, Ratio, CE_By_Dom:Deer_By_Dom, factor_key = TRUE)
Period_Ratios$Group.1 <- factor(Period_Ratios$Group.1, levels = c("Middle Iron Age", "Late Iron Age", "Iron Age Roman Transition", "Late Iron Age/Early Roman", "Early Roman", "Mid Roman", "Late Roman", "Early Saxon", "Middle Saxon", "Late Saxon", "Norman", "Medieval", "Early Modern", "Modern"))

Mapping_Master <- temp

#cleanup
temp["CE_By_Dom"][temp["CE_By_Dom"] == 0] <- NA
temp["CC_By_Dom"][temp["CC_By_Dom"] == 0] <- NA
temp["DD_By_Dom"][temp["DD_By_Dom"] == 0] <- NA
temp["Deer_By_Dom"][temp["Deer_By_Dom"] == 0] <- NA
```

```{r ratio graphs}
UK <- gisco_get_countries(country = "UK", resolution = 1)

ggplot(Meta_Period_Ratios, aes(y=Group.1, x=Ratio, fill = Ratio)) +
  geom_col()+
  facet_wrap(~Species)

ggplot(Meta_Period_Tots, aes(x=Group.1, y=Sum, fill = Species)) +
  geom_col()+
  theme(
    axis.text.x = element_text(angle = 45, vjust = 0.5)
  )

ggplot(Period_Ratios, aes(y=Group.1, x=Ratio, fill = Ratio)) +
  geom_col()+
  facet_wrap(~Species)


mybreaks <- c(0.0005, 0.001, 0.01, 0.1)
redperiod <- Mapping_Master %>%
  arrange(CE_By_Dom) %>%
  #mutate(name = factor(name, unique(name))) %>%
  ggplot() +
  geom_sf(data = UK, fill = "grey", alpha = 0.3) +
  geom_point(aes(x = Long, y = Lat, size = CE_By_Dom, color = CE_By_Dom, alpha = CE_By_Dom),shape = 20, stroke = FALSE) +
  scale_size_continuous(
    name = "Red to Domestic Ratio", trans = "log",
    range = c(0.1, 6), breaks = mybreaks
  ) +
  scale_alpha_continuous(
    name = "Red to Domestic Ratio", trans = "log",
    range = c(0.1, .9), breaks = mybreaks
  ) +
  scale_color_viridis_c(
    option = "magma", trans = "log",
    breaks = mybreaks, name = "Red to Domestic Ratio"
  ) +
  theme_void() +
  ylim(50, 59) +
  theme(text = element_text(color = "#22211d"),
    plot.margin = margin(r = 2, l = 2, unit = "cm"),
    plot.background = element_rect(fill = "#f5f5f2", color = NA),
    panel.background = element_rect(fill = "#f5f5f2", color = NA),
    plot.title = element_text(size = 14, hjust = 0.5, color = "#4e4d47"),
    legend.title = element_text(size = 8),
    legend.text = element_text(size = 8)) +
  facet_wrap(.~Meta_Period)
redperiod

mybreaks <- c(0.0001, 0.001, 0.01, 0.1)
allxdom <- Mapping_Master %>%
  arrange(CE_By_Dom) %>%
  #mutate(name = factor(name, unique(name))) %>%
  ggplot() +
  geom_sf(data = UK, fill = "grey", alpha = 0.3) +
  geom_point(aes(x = Long, y = Lat, size = Deer_By_Dom, color = Deer_By_Dom, alpha = Deer_By_Dom),shape = 20, stroke = FALSE) +
  scale_size_continuous(
    name = "Deer to Domestic Ratio", trans = "log",
    range = c(0.001, 6), breaks = mybreaks
  ) +
  scale_alpha_continuous(
    name = "Deer to Domestic Ratio", trans = "log",
    range = c(0.1, .9), breaks = mybreaks
  ) +
  scale_color_viridis_c(
    option = "magma", trans = "log",
    breaks = mybreaks, name = "Deer to Domestic Ratio"
  ) +
  theme_void() +
  ylim(50, 59) +
  theme(text = element_text(color = "#22211d"),
    plot.margin = margin(r = 2, l = 2, unit = "cm"),
    plot.background = element_rect(fill = "#f5f5f2", color = NA),
    panel.background = element_rect(fill = "#f5f5f2", color = NA),
    plot.title = element_text(size = 14, hjust = 0.5, color = "#4e4d47"),
    legend.title = element_text(size = 8),
    legend.text = element_text(size = 8)) + 
  facet_wrap(.~Meta_Period)

allxdom

```

```{r ratio widgets}

#all widget
temp <- temp %>%
  mutate(mytext = paste(
    "Site: ", Site, "\n",
    "Type: ", Site_Type, "\n",
    "Ratio: ", Deer_By_Dom,
    sep = ""
  ))
allxdomWIDGET <- temp %>%
  subset(!is.na(Deer_By_Dom)) %>%
  arrange(Deer_By_Dom) %>%
  ggplot() +
  geom_sf(data = UK, fill = "grey", alpha = 0.3) +
  geom_point(aes(
    x = Long, y = Lat, size = Deer_By_Dom, color = Deer_By_Dom, text = mytext,
    alpha = Deer_By_Dom
  )) +
  labs(
    title = "All Deer / Domestic"
  ) +
  xlim(-6, 2.5) +
  ylim(49, 55.5) +
  scale_size_continuous(range = c(0.5, 5),trans = "log", name = "Deer/Domestic") +
  scale_color_viridis_c(option = "inferno", trans = "log", name = "Deer/Domestic") +
  scale_alpha_continuous(trans = "log", name = "Deer/Domestic") +
  theme_void() + 
  guides(colour = guide_legend()) +
  facet_wrap(.~Meta_Period)
allxdomWIDGET
p <- ggplotly(allxdomWIDGET, tooltip = "text")
saveWidget(p, file=paste0( getwd(), "/bubblemapUKAll.html"))

#red widget
temp <- temp %>%
  mutate(mytext = paste(
    "Site: ", Site, "\n",
    "Type: ", Site_Type, "\n",
    "Ratio: ", CE_By_Dom,
    sep = ""
  ))
CervusxdomWIDGET <- temp %>%
  subset(!is.na(CE_By_Dom)) %>%
  arrange(CE_By_Dom) %>%
  ggplot() +
  geom_sf(data = UK, fill = "grey", alpha = 0.3) +
  geom_point(aes(
    x = Long, y = Lat, size = CE_By_Dom, color = CE_By_Dom, text = mytext,
    alpha = CE_By_Dom
  )) +
  labs(
    title = "Red Deer / Domestic"
  ) +
  xlim(-6, 2.5) +
  ylim(49, 55.5) +
  scale_size_continuous(range = c(0.5, 5),trans = "log", name = "Cervus/Domestic") +
  scale_color_viridis_c(option = "inferno", trans = "log", name = "Cervus/Domestic") +
  scale_alpha_continuous(trans = "log", name = "Cervus/Domestic") +
  theme_void() + 
  guides(colour = guide_legend()) +
  facet_wrap(.~Meta_Period)
CervusxdomWIDGET
p <- ggplotly(CervusxdomWIDGET, tooltip = "text")
saveWidget(p, file=paste0( getwd(), "/bubblemapUKRED.html"))

#fallow widget
temp <- temp %>%
  mutate(mytext = paste(
    "Site: ", Site, "\n",
    "Type: ", Site_Type, "\n",
    "Ratio: ", DD_By_Dom,
    sep = ""
  ))
DDxdomWIDGET <- temp %>%
  subset(!is.na(DD_By_Dom)) %>%
  arrange(DD_By_Dom) %>%
  ggplot() +
  geom_sf(data = UK, fill = "grey", alpha = 0.3) +
  geom_point(aes(
    x = Long, y = Lat, size = DD_By_Dom, color = DD_By_Dom, text = mytext,
    alpha = DD_By_Dom
  )) +
  labs(
    title = "Fallow Deer / Domestic"
  ) +
  xlim(-6, 2.5) +
  ylim(49, 55.5) +
  scale_size_continuous(range = c(0.5, 5), trans = "log", name = "Fallow/Domestic") +
  scale_color_viridis_c(option = "inferno", trans = "log", name = "Fallow/Domestic") +
  scale_alpha_continuous(trans = "log", name = "Fallow/Domestic") +
  theme_void() + 
  guides(colour = guide_legend()) +
  facet_wrap(.~Meta_Period)
allxdomWIDGET
p <- ggplotly(DDxdomWIDGET, tooltip = "text")
saveWidget(p, file=paste0( getwd(), "/bubblemapUKFallow.html"))

#roe widget
temp <- temp %>%
  mutate(mytext = paste(
    "Site: ", Site, "\n",
    "Type: ", Site_Type, "\n",
    "Ratio: ", CC_By_Dom,
    sep = ""
  ))
CCxdomWIDGET <- temp %>%
  subset(!is.na(CC_By_Dom)) %>%
  arrange(CC_By_Dom) %>%
  ggplot() +
  geom_sf(data = UK, fill = "grey", alpha = 0.3) +
  geom_point(aes(
    x = Long, y = Lat, size = CC_By_Dom, color = CC_By_Dom, text = mytext,
    alpha = CC_By_Dom
  )) +
  labs(
    title = "Roe Deer / Domestic"
  ) +
  xlim(-6, 2.5) +
  ylim(49, 55.5) +
  scale_size_continuous(range = c(0.5, 5), trans = "log", name = "Roe/Domestic") +
  scale_color_viridis_c(option = "inferno", trans = "log", name = "Roe/Domestic") +
  scale_alpha_continuous(trans = "log", name = "Roe/Domestic") +
  theme_void() +
  guides(colour = guide_legend()) +
  facet_wrap(.~Meta_Period)
CCxdomWIDGET
p <- ggplotly(CCxdomWIDGET, tooltip = "text")
saveWidget(p, file=paste0( getwd(), "/bubblemapUKRoe.html"))
```

```{r redone heat maps basic}
#Import Base Map
UK_crs <- st_crs(27700)
UK <- gisco_get_countries(country = "UK", resolution = 1)
UK <- st_set_crs(UK, st_crs(UK_crs))

#Red All
#sorting data
HEAT_temp <- Mapping_Master %>%
  subset(Cervus > 0)
HEAT_temp <- st_as_sf(HEAT_temp, coords = c("Long", "Lat"))
HEAT_temp <- st_set_crs(HEAT_temp, st_crs(27700))
HEAT_temp <- as.ppp(HEAT_temp$geometry, W = as.owin(UK))
#density mapping
HEAT_temp <- stars::st_as_stars(density(HEAT_temp, dimyx = 300))
HEAT_temp <- st_as_sf(HEAT_temp)
plot_density <- ggplot() +
  geom_sf(data = HEAT_temp, aes(fill = v), color = NA) +
  scale_fill_viridis_c(option = "turbo", guide = "none") +
  labs(title = "Red_All")
plot_density
ggsave("Red_Heat.jpg")

#Roe All
#sorting data
HEAT_temp <- Mapping_Master %>%
  subset(Cap > 0)
HEAT_temp <- st_as_sf(HEAT_temp, coords = c("Long", "Lat"))
HEAT_temp <- st_set_crs(HEAT_temp, st_crs(27700))
HEAT_temp <- as.ppp(HEAT_temp$geometry, W = as.owin(UK))
#density mapping
HEAT_temp <- stars::st_as_stars(density(HEAT_temp, dimyx = 300))
HEAT_temp <- st_as_sf(HEAT_temp)
plot_density <- ggplot() +
  geom_sf(data = HEAT_temp, aes(fill = v), color = NA) +
  scale_fill_viridis_c(option = "turbo", guide = "none")+
  labs(title = "Roe_All")
plot_density
ggsave("Roe_Heat.jpg")

#Dama All
#sorting data
HEAT_temp <- Mapping_Master %>%
  subset(Dama > 0)
HEAT_temp <- st_as_sf(HEAT_temp, coords = c("Long", "Lat"))
HEAT_temp <- st_set_crs(HEAT_temp, st_crs(27700))
HEAT_temp <- as.ppp(HEAT_temp$geometry, W = as.owin(UK))
#density mapping
HEAT_temp <- stars::st_as_stars(density(HEAT_temp, dimyx = 300))
HEAT_temp <- st_as_sf(HEAT_temp)
plot_density <- ggplot() +
  geom_sf(data = HEAT_temp, aes(fill = v), color = NA) +
  scale_fill_viridis_c(option = "turbo", guide = "none")+
  labs(title = "Dama_All")
plot_density
ggsave("Dama_Heat.jpg")
```

```{r Red Heat Period}
#Import Base Map
UK_crs <- st_crs(27700)
UK <- gisco_get_countries(country = "UK", resolution = 1)
UK <- st_set_crs(UK, st_crs(UK_crs))

#Iron Age
HEAT_temp <- Mapping_Master %>%
  subset(Cervus > 0)
HEAT_temp <- st_as_sf(HEAT_temp, coords = c("Long", "Lat"))
HEAT_temp <- st_set_crs(HEAT_temp, st_crs(27700))
HEAT_temp <- subset(HEAT_temp, Meta_Period == "Iron Age")
HEAT_temp <- as.ppp(HEAT_temp$geometry, W = as.owin(UK))
HEAT_temp <- stars::st_as_stars(density(HEAT_temp, dimyx = 300))
HEAT_temp <- st_as_sf(HEAT_temp)
#plotting
plot_IA_density <- ggplot() +
  geom_sf(data = HEAT_temp, aes(fill = v), color = NA) +
  theme_void() +
  labs(title = "Iron Age Red") +
  scale_fill_viridis_c(option = "turbo", guide = "none")
ggsave("IA_Heat.jpg")

#Roman
HEAT_temp <- Mapping_Master %>%
  subset(Cervus > 0)
HEAT_temp <- st_as_sf(HEAT_temp, coords = c("Long", "Lat"))
HEAT_temp <- st_set_crs(HEAT_temp, st_crs(27700))
HEAT_temp <- subset(HEAT_temp, Meta_Period == "Roman")
HEAT_temp <- as.ppp(HEAT_temp$geometry, W = as.owin(UK))
HEAT_temp <- stars::st_as_stars(density(HEAT_temp, dimyx = 300))
HEAT_temp <- st_as_sf(HEAT_temp)
#plotting
plot_IA_density <- ggplot() +
  geom_sf(data = HEAT_temp, aes(fill = v), color = NA) +
  theme_void() +
  labs(title = "Roman Red") +
  scale_fill_viridis_c(option = "turbo", guide = "none")
ggsave("Roman_Heat.jpg")

#Medieval
HEAT_temp <- Mapping_Master %>%
  subset(Cervus > 0)
HEAT_temp <- st_as_sf(HEAT_temp, coords = c("Long", "Lat"))
HEAT_temp <- st_set_crs(HEAT_temp, st_crs(27700))
HEAT_temp <- subset(HEAT_temp, Meta_Period == "Medieval")
HEAT_temp <- as.ppp(HEAT_temp$geometry, W = as.owin(UK))
HEAT_temp <- stars::st_as_stars(density(HEAT_temp, dimyx = 300))
HEAT_temp <- st_as_sf(HEAT_temp)
#plotting
plot_IA_density <- ggplot() +
  geom_sf(data = HEAT_temp, aes(fill = v), color = NA) +
  theme_void() +
  labs(title = "Medieval Red") +
  scale_fill_viridis_c(option = "turbo", guide = "none")
ggsave("Medieval_Heat.jpg")

#Post_Medieval
HEAT_temp <- Mapping_Master %>%
  subset(Cervus > 0)
HEAT_temp <- st_as_sf(HEAT_temp, coords = c("Long", "Lat"))
HEAT_temp <- st_set_crs(HEAT_temp, st_crs(27700))
HEAT_temp <- subset(HEAT_temp, Meta_Period == "Post_Medieval")
HEAT_temp <- as.ppp(HEAT_temp$geometry, W = as.owin(UK))
HEAT_temp <- stars::st_as_stars(density(HEAT_temp, dimyx = 300))
HEAT_temp <- st_as_sf(HEAT_temp)
#plotting
plot_IA_density <- ggplot() +
  geom_sf(data = HEAT_temp, aes(fill = v), color = NA) +
  theme_void() +
  labs(title = "Post_Medieval Red") +
  scale_fill_viridis_c(option = "turbo", guide = "none")
ggsave("Post_Medieval_Heat.jpg")
```

```{r Fallow Heat Period}
#Import Base Map
UK_crs <- st_crs(27700)
UK <- gisco_get_countries(country = "UK", resolution = 1)
UK <- st_set_crs(UK, st_crs(UK_crs))

#Iron Age
HEAT_temp <- Mapping_Master %>%
  subset(Dama > 0)
HEAT_temp <- st_as_sf(HEAT_temp, coords = c("Long", "Lat"))
HEAT_temp <- st_set_crs(HEAT_temp, st_crs(27700))
HEAT_temp <- subset(HEAT_temp, Meta_Period == "Iron Age")
HEAT_temp <- as.ppp(HEAT_temp$geometry, W = as.owin(UK))
HEAT_temp <- stars::st_as_stars(density(HEAT_temp, dimyx = 300))
HEAT_temp <- st_as_sf(HEAT_temp)
#plotting
plot_IA_density <- ggplot() +
  geom_sf(data = HEAT_temp, aes(fill = v), color = NA) +
  theme_void() +
  labs(title = "Iron Age Dama") +
  scale_fill_viridis_c(option = "turbo", guide = "none")
ggsave("IA_Heat Dama.jpg")

#Roman
HEAT_temp <- Mapping_Master %>%
  subset(Dama > 0)
HEAT_temp <- st_as_sf(HEAT_temp, coords = c("Long", "Lat"))
HEAT_temp <- st_set_crs(HEAT_temp, st_crs(27700))
HEAT_temp <- subset(HEAT_temp, Meta_Period == "Roman")
HEAT_temp <- as.ppp(HEAT_temp$geometry, W = as.owin(UK))
HEAT_temp <- stars::st_as_stars(density(HEAT_temp, dimyx = 300))
HEAT_temp <- st_as_sf(HEAT_temp)
#plotting
plot_IA_density <- ggplot() +
  geom_sf(data = HEAT_temp, aes(fill = v), color = NA) +
  theme_void() +
  labs(title = "Roman Dama") +
  scale_fill_viridis_c(option = "turbo", guide = "none")
ggsave("Roman_Heat Dama.jpg")

#Medieval
HEAT_temp <- Mapping_Master %>%
  subset(Dama > 0)
HEAT_temp <- st_as_sf(HEAT_temp, coords = c("Long", "Lat"))
HEAT_temp <- st_set_crs(HEAT_temp, st_crs(27700))
HEAT_temp <- subset(HEAT_temp, Meta_Period == "Medieval")
HEAT_temp <- as.ppp(HEAT_temp$geometry, W = as.owin(UK))
HEAT_temp <- stars::st_as_stars(density(HEAT_temp, dimyx = 300))
HEAT_temp <- st_as_sf(HEAT_temp)
#plotting
plot_IA_density <- ggplot() +
  geom_sf(data = HEAT_temp, aes(fill = v), color = NA) +
  theme_void() +
  labs(title = "Medieval Dama") +
  scale_fill_viridis_c(option = "turbo", guide = "none")
ggsave("Medieval_Heat Dama.jpg")

#Post_Medieval
HEAT_temp <- Mapping_Master %>%
  subset(Dama > 0)
HEAT_temp <- st_as_sf(HEAT_temp, coords = c("Long", "Lat"))
HEAT_temp <- st_set_crs(HEAT_temp, st_crs(27700))
HEAT_temp <- subset(HEAT_temp, Meta_Period == "Post_Medieval")
HEAT_temp <- as.ppp(HEAT_temp$geometry, W = as.owin(UK))
HEAT_temp <- stars::st_as_stars(density(HEAT_temp, dimyx = 300))
HEAT_temp <- st_as_sf(HEAT_temp)
#plotting
plot_IA_density <- ggplot() +
  geom_sf(data = HEAT_temp, aes(fill = v), color = NA) +
  theme_void() +
  labs(title = "Post_Medieval Dama") +
  scale_fill_viridis_c(option = "turbo", guide = "none")
ggsave("Post_Medieval_Heat Dama.jpg")
```

```{r Roe Heat Period}
#Import Base Map
UK_crs <- st_crs(27700)
UK <- gisco_get_countries(country = "UK", resolution = 1)
UK <- st_set_crs(UK, st_crs(UK_crs))

#Iron Age
HEAT_temp <- Mapping_Master %>%
  subset(Cap > 0)
HEAT_temp <- st_as_sf(HEAT_temp, coords = c("Long", "Lat"))
HEAT_temp <- st_set_crs(HEAT_temp, st_crs(27700))
HEAT_temp <- subset(HEAT_temp, Meta_Period == "Iron Age")
HEAT_temp <- as.ppp(HEAT_temp$geometry, W = as.owin(UK))
HEAT_temp <- stars::st_as_stars(density(HEAT_temp, dimyx = 300))
HEAT_temp <- st_as_sf(HEAT_temp)
#plotting
plot_IA_density <- ggplot() +
  geom_sf(data = HEAT_temp, aes(fill = v), color = NA) +
  theme_void() +
  labs(title = "Iron Age Cap") +
  scale_fill_viridis_c(option = "turbo", guide = "none")
ggsave("IA_Heat Cap.jpg")

#Roman
HEAT_temp <- Mapping_Master %>%
  subset(Cap > 0)
HEAT_temp <- st_as_sf(HEAT_temp, coords = c("Long", "Lat"))
HEAT_temp <- st_set_crs(HEAT_temp, st_crs(27700))
HEAT_temp <- subset(HEAT_temp, Meta_Period == "Roman")
HEAT_temp <- as.ppp(HEAT_temp$geometry, W = as.owin(UK))
HEAT_temp <- stars::st_as_stars(density(HEAT_temp, dimyx = 300))
HEAT_temp <- st_as_sf(HEAT_temp)
#plotting
plot_IA_density <- ggplot() +
  geom_sf(data = HEAT_temp, aes(fill = v), color = NA) +
  theme_void() +
  labs(title = "Roman Cap") +
  scale_fill_viridis_c(option = "turbo", guide = "none")
ggsave("Roman_Heat Cap.jpg")

#Medieval
HEAT_temp <- Mapping_Master %>%
  subset(Cap > 0)
HEAT_temp <- st_as_sf(HEAT_temp, coords = c("Long", "Lat"))
HEAT_temp <- st_set_crs(HEAT_temp, st_crs(27700))
HEAT_temp <- subset(HEAT_temp, Meta_Period == "Medieval")
HEAT_temp <- as.ppp(HEAT_temp$geometry, W = as.owin(UK))
HEAT_temp <- stars::st_as_stars(density(HEAT_temp, dimyx = 300))
HEAT_temp <- st_as_sf(HEAT_temp)
#plotting
plot_IA_density <- ggplot() +
  geom_sf(data = HEAT_temp, aes(fill = v), color = NA) +
  theme_void() +
  labs(title = "Medieval Cap") +
  scale_fill_viridis_c(option = "turbo", guide = "none")
ggsave("Medieval_Heat Cap.jpg")

#Post_Medieval
HEAT_temp <- Mapping_Master %>%
  subset(Cap > 0)
HEAT_temp <- st_as_sf(HEAT_temp, coords = c("Long", "Lat"))
HEAT_temp <- st_set_crs(HEAT_temp, st_crs(27700))
HEAT_temp <- subset(HEAT_temp, Meta_Period == "Post_Medieval")
HEAT_temp <- as.ppp(HEAT_temp$geometry, W = as.owin(UK))
HEAT_temp <- stars::st_as_stars(density(HEAT_temp, dimyx = 300))
HEAT_temp <- st_as_sf(HEAT_temp)
#plotting
plot_IA_density <- ggplot() +
  geom_sf(data = HEAT_temp, aes(fill = v), color = NA) +
  theme_void() +
  labs(title = "Post_Medieval Cap") +
  scale_fill_viridis_c(option = "turbo", guide = "none")
ggsave("Post_Medieval_Heat Cap.jpg")
```

```{r AEA}
### make the distribution maps data prep
ALL_Grid <- read_excel("Mapping_Master_Complete.xlsx")
ALL_Grid$Meta_Period <- factor(ALL_Grid$Meta_Period, levels = c("Iron Age", "Roman", "Anglo_Saxon", "Medieval", "Post_Medieval", "Modern"))
ALL_Grid <- ALL_Grid[c(1,3,8,9,10,13,14)]
colnames(ALL_Grid)[3] <- "Cervus elaphus"
colnames(ALL_Grid)[4] <- "Capreolus capreolus"
colnames(ALL_Grid)[5] <- "Dama dama"
#make it long - merge everything
ALL_Grid$info <- paste(ALL_Grid$Site, ALL_Grid$Meta_Period, ALL_Grid$Lat, ALL_Grid$Long, sep = "###")
ALL_Grid <- ALL_Grid[c(3,4,5,8)]
#melt it
ALL_Grid <- melt(ALL_Grid, id = c("info"), variable.name = "Species")
ALL_Grid <- ALL_Grid %>% drop_na()
#separate it back out again
ALL_Grid <- ALL_Grid %>%
  separate(info, into = c("Site", "Meta_Period", "Lat", "Long"), sep = "###")

# make distribution maps - map creation
#Import UK Base map etc. see above
UK <- gisco_get_countries(country = "UK", resolution = 1)
UK <- st_transform(UK, st_crs(27700))
UK_Grid <- UK %>%
  st_make_grid(cellsize = c(10000,10000))
UK_Grid_Map <- st_intersection(UK_Grid, UK) %>% 
  st_as_sf() %>% 
  mutate(grid_id = 1:n())
UK <- st_transform(UK, st_crs("WGS84"))
UK_Grid_Map <- st_transform(UK_Grid_Map, st_crs("WGS84"))
#Make Data Gel with the grid
AEAEA <- ALL_Grid
AEAEA <- AEAEA[,c("Meta_Period", "Species", "Lat", "Long")]
AEAEA$Lat <- as.numeric(AEAEA$Lat)
AEAEA$Long <- as.numeric(AEAEA$Long)
coordinates(AEAEA)=~Long+Lat
proj4string(AEAEA) <- CRS("+proj=longlat +datum=WGS84")
AEAEA <- st_as_sf(AEAEA)

AEAGrid <- UK_Grid_Map %>% 
  st_join(AEAEA) %>% 
  group_by(grid_id)
AEAGrid <- AEAGrid %>% drop_na()
AEAGrid <- AEAGrid[,c(3,1,2,4)]
AEAGrid$Meta_Period <- factor(AEAGrid$Meta_Period, levels = c("Iron Age", "Roman", "Anglo_Saxon", "Medieval", "Post_Medieval", "Modern"))

ggplot() +
  geom_sf(data = UK) +
  geom_sf(data = filter(AEAGrid, Meta_Period == "Iron Age"), aes(fill = Species), alpha = 0.5)+
  theme(
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    axis.title = element_blank(),
    panel.grid = element_blank()
  ) +
  labs(
    title = "Iron Age"
  ) +
  coord_sf(xlim = c(-7.5, 2), ylim = c(49.8, 56), expand = FALSE) 

ggsave("AEAIA.png", dpi = 1200)

ggplot() +
  geom_sf(data = UK) +
  geom_sf(data = filter(AEAGrid, Meta_Period == "Roman"), aes(fill = Species), alpha = 0.5)+
  theme(
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    axis.title = element_blank(),
    panel.grid = element_blank()
  ) +
  labs(
    title = "Roman"
  ) +
  coord_sf(xlim = c(-7.5, 2), ylim = c(49.8, 56), expand = FALSE) 

ggsave("AEARom.png", dpi = 1200)

ggplot() +
  geom_sf(data = UK) +
  geom_sf(data = filter(AEAGrid, Meta_Period == "Anglo_Saxon"), aes(fill = Species), alpha = 0.5)+
  theme(
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    axis.title = element_blank(),
    panel.grid = element_blank()
  ) +
  labs(
    title = "Anglo Saxon"
  ) +
  coord_sf(xlim = c(-7.5, 2), ylim = c(49.8, 56), expand = FALSE) 
ggsave("AEAAS.png", dpi = 1200)

ggplot() +
  geom_sf(data = UK) +
  geom_sf(data = filter(AEAGrid, Meta_Period == "Medieval"), aes(fill = Species), alpha = 0.5)+
  theme(
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    axis.title = element_blank(),
    panel.grid = element_blank()
  ) +
  labs(
    title = "Medieval"
  ) +
  coord_sf(xlim = c(-7.5, 2), ylim = c(49.8, 56), expand = FALSE) 
ggsave("AEAMed.png", dpi = 1200)

ggplot() +
  geom_sf(data = UK) +
  geom_sf(data = filter(AEAGrid, Meta_Period == "Post_Medieval"), aes(fill = Species), alpha = 0.5)+
  theme(
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    axis.title = element_blank(),
    panel.grid = element_blank()
  ) +
  labs(
    title = "Post Medieval"
  ) +
  coord_sf(xlim = c(-7.5, 2), ylim = c(49.8, 56), expand = FALSE) 
ggsave("AEAPM.png", dpi = 1200)
```

```{r AEA 2nd bit}
maps <- read.xlsx("RD_JS.xlsx", sheet = "AEA maps")
graphs <- read.xlsx("RD_JS.xlsx", sheet = "AEA graphs")
graphs <- graphs[c(2,3)]
graphs$Period <- factor(graphs$Period, levels = c("Mesolithic", "Neolithic", "Bronze Age", "Iron Age", "Roman", "Medieval", "Modern"))
maps$Period <- factor(maps$Period, levels = c("Mesolithic", "Neolithic", "Bronze Age", "Iron Age", "Roman", "Medieval", "Modern"))

world <- ne_countries(scale = "medium", returnclass = "sf")
class(world)

ggplot(data = world) +
  geom_sf() +
  theme_bw() +
  coord_sf(xlim = c(-8, 17.5), ylim = c(35.5, 59), expand = FALSE) +
  xlab("Longitude") + ylab("Latitude") +
  geom_label_repel(data = maps, aes(label = Site, x = Long, y = Lat, fill = Period), size = 2, nudge_x = 0.5,label.size = NA , color = "#000000", segment.colour = "#000000", max.overlaps  = Inf, min.segment.length = 0) +
  geom_point(data = maps, aes(x = Long, y= Lat)) +
  scale_fill_manual(name = "Period", aesthetics = c("fill", "segment.color"), values = c("#8dd3c7", "#ffffb3", "#bebada", "#fb8072", "#80b1d3", "#fdb462", "#b3de69"), labels = c("Mesolithic", "Neolithic", "Bronze Age", "Iron Age", "Roman", "Medieval", "Modern")) +
  guides(fill = guide_legend(override.aes = aes(label = "")))

ggsave("AEASiteMap.png", dpi = 1200)

ggplot(graphs, aes(x=MWS, y=..count.., fill = Period)) +
  geom_bar() +
  labs(
    y = "Proportion",
    x = "MWS"
    ) +
  theme(
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank()
  ) +
  scale_y_continuous(expand = c(0,0)) +
  scale_fill_manual(values = c("#8dd3c7", "#ffffb3", "#bebada", "#fb8072", "#80b1d3", "#fdb462", "#b3de69")) +
  facet_wrap(~Period, nrow = 2, scales = "free_y")

ggsave("AEAGraph.png", dpi = 1200)
```

